# fly.toml app configuration file generated for presentations-snowy-pond-4205-spring-haze-7202-morning-firefly-2107-hidden-forest-9058 on 2023-11-22T15:20:13+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "presentations-snowy-pond-4205-spring-haze-7202-morning-firefly-2107-hidden-forest-9058"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3999
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
