# fly.toml app configuration file generated for noebs-presentation-winter-thunder-4857-billowing-log-7426 on 2023-11-22T16:35:05+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "noebs-presentation"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3999
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
